### PR TITLE
Add support for orangepi-plus2e

### PR DESCRIPTION
**Pull request by ajlennon**
Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
Hi @ajlennon thanks for the PR.
I have a few things to ask you.
Can you follow the contributions guideline from https://github.com/balena-os/balena-allwinner#pull-requests? (most notable, we need at least 1 `Changelog-entry` in one of your commits in this PR)
Also, can you split the PR in multiple commits, one for each file change?
Also, can you add `community` in the coffee file like in https://github.com/balena-os/balena-allwinner/blob/master/orange-pi-zero.coffee#L11?

**Comment by ajlennon** [comment]
Will do! Thanks for the feedback

**Comment by ajlennon** [comment]
https://github.com/balena-os/balena-allwinner/pull/71

**Pull request closed without merging**
